services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  backend:
    build: .
    environment:
      - dbUrl=mongodb://mongo:27017/mynds-sistema
      - PORT=4444
      - JWT_SECRET=segredo-de-teste
    ports:
      - "4444:4444"
    depends_on:
      - mongo
